general.import = [
  "~/.config/alacritty/theme/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 5

# decorations = "Buttonless"
decorations = "None" #for linux also

opacity = 0.85
blur = true

option_as_alt = "Both"

[font]
normal.family = "0xProto Nerd Font"
normal.style = "Regular"
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0
size = 11
